Feature/fix link
Naokichi55/joint_dev_task pull request #1
Opened 2023-06-07 00:51 UTC by Naokichi55

Ruby課題（基礎）Q6~Q10を解答しました。レビューの程お願いします。

2023-06-07 01:27 UTC, T-Tsujii requested changes
お疲れ様です。コメントした箇所以外はOKです！

2023-06-07 01:27 UTC, T-Tsujii commented on task.rb
> +  array.map!{|array| array.to_i}
｀&:｀を使用するともっと簡潔に書くことができますよ！

2023-06-07 01:27 UTC, T-Tsujii commented on task.rb
> +  upper_case_programming_languages = programming_languages.map{|word| word.upcase}
こちらもQ7同様｀&:｀を使用するともっと簡潔に書くことができます。

ただ、今の回答ですと、`p programming_languages` が正しい結果にはならないのではないでしょうか？

2023-06-07 12:57 UTC, Naokichi55 commented on task.rb
> +  array.map!{|array| array.to_i}
コメントありがとうございます。
｀&:｀を使用し簡潔に書いてみました。
お手数ですが再度レビューの程お願いします。

2023-06-07 13:01 UTC, Naokichi55 commented on task.rb
> +  upper_case_programming_languages = programming_languages.map{|word| word.upcase}
コメントありごうとざいます。Q7同様に｀&:｀を使用し書いてみました。お手数ですが再度レビューの程お願いします。
ご指摘いただいた ' p programming_languages ' は正しい結果になっておりませんでした。
不完全なものを提出してしまい申し訳ございませんでした。

2023-06-07 13:09 UTC, T-Tsujii reviewed
q10までOKです！お疲れ様です！

2023-06-08 10:31 UTC, Naokichi55 commented
> q10までOKです！お疲れ様です！

2023-06-08 10:44 UTC, merged