Q11, Q12, Q13を解答しました。
Naokichi55/joint_dev_task pull request #2
Opened 2023-06-10 08:35 UTC by Naokichi55

Ruby(基礎)　Q11, Q12, Q13を解答しました。レビューをお願いします。

2023-06-10 12:11 UTC, T-Tsujii requested changes
Q12,13はOKです。Q11は修正してみて下さい！

2023-06-10 12:11 UTC, T-Tsujii commented on task.rb
> +  sports.flatten!(&:uniq)
このコードでは例えば `サッカー` が重複したままですね。

2023-06-11 02:14 UTC, Naokichi55 commented on task.rb
> +  sports.flatten!(&:uniq)
修正してみました。お手数ですが再度レビューの程お願いします。

2023-06-11 08:33 UTC, T-Tsujii approved these changes
Q11もOKです！

2023-06-12 09:45 UTC, merged