Ruby(基礎) Q14,Q15,Q16を解答しました。
Naokichi55/joint_dev_task pull request #3
Opened 2023-06-17 07:22 UTC by Naokichi55

Ruby(基礎)Q14,Q15,Q16を解答しました。お手数ですがレビューの程お願いします。

2023-06-17 09:15 UTC, T-Tsujii requested changes
Q14以外はOKです！

2023-06-17 09:15 UTC, T-Tsujii commented on task.rb
> +    p data1
メソッドが存在するので探してみて下さい。

2023-06-18 02:45 UTC, Naokichi55 commented on task.rb
> +    p data1
ご確認ありがとうございます。keysメソッドを使用してみました。お手数ですが再度レビューの程お願いします。

2023-06-18 04:27 UTC, T-Tsujii approved these changes
OKです。お疲れ様です！

2023-07-03 05:59 UTC, merged